version: 2.1
orbs:
  maven: circleci/maven@1.0

jobs:
  build:
    executor: maven/default
    steps:
      - checkout

      # Restore cached Maven dependencies to speed up the build
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}

      # Install JDK and Maven
      - setup_remote_docker:
          version: 20.10.7
      - maven/install-jdk

      # Build and test the Java application
      - run:
          name: Build and Test
          command: mvn clean test

      # Save Maven dependencies to cache for future builds
      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

workflows:
  version: 2
  build-test:
    jobs:
      - build
